### PR TITLE
i13 - support ajax data sources

### LINKED ISSUE #13: Cant handle ajax source
doesn't work if there's no `data` option specified in the DT options and instead `ajaxSource` or `ajax.url` is used. Most of the times in real world, data tables is used with ajax data.

### PR DESCRIPTION
**Pull request by hillalex**
This PR adds minimal support for ajax data sources - that is, support for the initial provision of an ajax data source, without support for full server-side processing or for ajax related API methods.

Closes #13 although not #17

### CODE REVIEW

File: treeTable.js [hunk 1]
```diff
@@ -118,21 +116,46 @@
 
     const TreeTable = function (element, options) {
         const self = this;
+        this.$el = $(element);
+        if (options.data) {
+            this.init(options);
+        } else if (options.ajax) {
+            this.$dummy = $("<table></table>");
```
Comment (EmmaLRussell) [inline treeTable.js:123]: So this uses DataTable's ajax support, to load ajax data into a dummy DT then handle the event on completion of that load to clean up the dummy table and set its own data with data built from the loaded raw json plus settings, using DT's internal method `_fnAjaxDataSrc`? 
If not, then this could probably use a comment! If so, I still wouldn't object to a brief comment on general strategy and what `_fnAjaxDataSrc` is!

**Review by EmmaLRussell — COMMENTED** [review]
So you lasted, what, a week? :laughing: 

LGTM. Maybe include a test error case? Does it deal gracefully with e.g data url doesn't exist?

File: treeTable.js (hunk 1 above)
Comment (hillalex) [reply treeTable.js:123]: Yes, you got it, but will add comment!

**Comment by hillalex** [comment]
About a week yeah :laughing:  Great suggestion, thanks, turns out it did need a null check in there to handle errors gracefully. Have commented code also.

**Review by EmmaLRussell — APPROVED** [review]
